### ISSUE TITLE
有时打完后不会自动统计成绩

### ISSUE THREAD

**Issue by Frefreak** [owenyang0/easy-typer#11]
![image](https://user-images.githubusercontent.com/7122156/226072580-2944c75e-877b-4db3-b4c9-92c36ea22633.png)
![image](https://user-images.githubusercontent.com/7122156/226072896-a700fb76-9833-4089-b2d6-3571d2809fc8.png)

如图，就一直等在这，要按enter或 空格再退格 才能触发，概率不算特别低。

Archlinux
Firefox 110.0.1 (64-bit)
fcitx5 + fcitx5-rime 包 + 虎码秃版的配置

**Comment by owenyang0** [comment]
这个主要跟输入法有关系，可以试试不同的输入法，看还有问题吗？

**Comment by Frefreak** [comment]
可以先关了，有空时我把代码拉下来研究下看看
