### ISSUE TITLE
关于统计击键数的问题（及firefox和chrome统计值差别较大的问题)

### ISSUE THREAD

**Issue by Frefreak** [owenyang0/easy-typer#12]
空格数应该是算入击键数的吧，这样算每个“人”应该是2击？（虎码：j 空格）
不过不管怎样统计的，同样的输入我发现在chrome中算出来的击键数会明显高于在firefox里

#### firefox

00:00:02.650 开始打第一个字符j
00:00:40.783 最后一个‘人’上屏

每个‘人’2击键，22个‘人’，44击键，平均`44 / (40.783 - 2.650) = 1.1538`，统计`0.97`

https://user-images.githubusercontent.com/7122156/226076406-c8305730-2aee-4cf0-ae92-83062c461fce.mp4

#### chrome

00:00:03.417 开始打第一个字符j
00:00:44.900 最后一个‘人’上屏

每个‘人’2击键，22个‘人’，44击键，平均`44 / (44.9 - 3.417) = 1.0607`，统计`1.59`

https://user-images.githubusercontent.com/7122156/226076448-0c380856-b7e9-4466-84d5-2f7b8858f8a8.mp4

如果算法没错，那看起来firefox就比较准确，chrome统计的多了（一换chrome前500十字轻松上6，白高兴了 :cry: )

但是印象中这个的实现应该主要是在chrome下测试的吧，正常来说chrome里应该验证过？

**Comment by Frefreak** [comment]
Archlinux
Firefox 110.0.1 (64-bit)
103.0.5060.134

**Comment by Frefreak** [comment]
类似#11， 先关了

**Comment by bczhc** [comment]
Arch Chrome确认遇到此问题。可以追踪下同样是这位提的fcitx5-rime的issue：https://github.com/fcitx/fcitx5/issues/748
