### ISSUE TITLE
粘贴发文失效了

### ISSUE THREAD

**Issue by bczhc** [owenyang0/easy-typer#2]
感谢开发这个很棒的网页版跟打器。但粘贴发文又有问题了。之前是没有问题的，不知什么时候开始有问题了。

在Firefox中对输入框Ctrl+V没有反应，但Chromium中可以发文。

还有点击“手动”时弹出的框里面Ctrl+V，提示“当前正在发文中, 请先结束发文后再试”，但“结束发文”按钮得点两次，并且还是不能粘贴文本进去。Firefox和Chromium都是如此。

Chromium 109.0.5414.119<br>Firefox 109.0<br>Arch linux 6.1.8<br>fcitx5-rime

**Comment by owenyang0** [comment]
感谢使用与反馈👍

我看了一下确实有点问题：在打开文本框的时候，没有处理好粘贴的事件。
目前在版本24已经修复，可以强刷一下页面，并退出重进再试一下。

**Comment by bczhc** [comment]
嗯现在可以手动发文中粘贴了，但输入框中不能粘贴发文。以前有这个功能很方便的。

**Comment by bczhc** [comment]
See #3
