### ISSUE TITLE
打完之后成绩复制，会话切出后就会提示“浏览器不支持复制”

### ISSUE THREAD

**Issue by bczhc** [owenyang0/easy-typer#3]
现象与复现：
1. 发文，跟打一遍，这时就认为复制功能是好的。
2. 按Ctrl+T打开一个新标签页，再按Ctrl+W关闭
3. 这时会回到原来的跟打器页面，不要动鼠标，按F3重打，跟打一遍，这时打完之后它就会提示“浏览器不支持复制”
4. 这时再F3重打，再点一下下面的输入框，再跟打，复制功能又好了。

这是我能找到的最小稳定复现的步骤了，实际上正常使用的时候，有的时候就会莫名其妙的出现这个问题，刚才试的时候也没找到具体的规律。比如在十字一组打字时，每组都会提示不支持复制，但即使像上面步骤四一样点了输入框还是提示复制失败。

视频演示：
<video src="https://user-images.githubusercontent.com/49330580/219830410-f09063c9-013f-405e-bafc-7ffdab001f9c.webm"/>

**Comment by owenyang0** [comment]
应该是浏览器的权限问题：
1. navigator.clipboard 仅支持通过 HTTPS 提供的页面。为了防止滥用，只有当页面处于活动选项卡时才允许剪贴板访问。
2. 活动选项卡中的页面可以在不请求权限的情况下写入剪贴板，但从剪贴板中读取始终需要权限。

因为你从别一个Tab切换回来的时候，鼠标没动没能激活这个页面，导致浏览器复制无效。

> 这个问题，跟你提的issue2：粘贴发文失效了 #2 应该是类似的，建议检查一下浏览器权限，或更换浏览器。

**建议：**
1. 可以试试Chrome(我是基于Chrome开发的)
2. 如果复制不成功，会将成绩展示出来(10s)，供用户复制。如图

<img width="700" alt="image" src="https://user-images.githubusercontent.com/2222167/221858847-4a7740e3-eb4f-4e4a-b2e0-7533d3ecbd87.png">

**Comment by owenyang0** [comment]
Firefox就是支持不好，看这里：https://bugzilla.mozilla.org/show_bug.cgi?id=1560373
我后面把这个代码去掉吧

**Comment by bczhc** [comment]
好吧那就不管了。
