### ISSUE TITLE
加入非正规符号替换的功能

### ISSUE THREAD

**Issue by bczhc** [owenyang0/easy-typer#4]
像小启跟打器一样。比如我今天打虎码赛文时遇到的一个省略号，`⋯`（MIDLINE HORIZONTAL ELLIPSIS）不是一般所用的那个`…`（HORIZONTAL ELLIPSIS），希望这种都能自动替换。

还有这个跟打器会考虑发群赛文还有什么什么杯的那种吗？

**Comment by owenyang0** [comment]
精力有限，暂时不会去支持了

**Comment by owenyang0** [comment]
可以试试版本(32)，新增符号替换功能

https://typer.owenyang.top/

<img width="193" alt="image" src="https://user-images.githubusercontent.com/2222167/223006023-0924e810-c0fd-478e-a133-7b6d1da0af4e.png">

**Comment by bczhc** [comment]
还有像ZWSP（U+200B）这种乱七八糟的空格
