### ISSUE TITLE
第五码不能顶屏

### ISSUE THREAD

**Issue by dnxxymcj** [owenyang0/easy-typer#8]
非常感谢作者Thanks♪(･ω･)ﾉ
第五码不能顶屏

macos 网页版，虎码单字

https://user-images.githubusercontent.com/7660888/222944693-bff4e523-bd30-402e-a97f-4023b2f7d1cc.mov

**Comment by bczhc** [comment]
Em这不应该是输入法的问题么。

**Comment by dnxxymcj** [comment]
> Em这不应该是输入法的问题么。

嗯。

**Comment by owenyang0** [comment]
Rime的配置问题，关闭拆分即可
